"""care modülünün varsayılan hizmet türleri."""

DEFAULT_SERVICE_TYPES = [
    {
        'slug': 'evde-bakim',
        'name': 'Evde bakım desteği',
        'description': 'Kişisel bakım, yemek ve günlük işlerde evde destek.',
        'name_en': 'Home care support',
        'description_en': 'Personal care, meals and help with daily tasks at home.',
        'icon': 'home-care',
        'sort_order': 10,
    },
    {
        'slug': 'refakat',
        'name': 'Refakat ve sohbet',
        'description': 'Yalnız kalmasın diye düzenli ziyaret ve sohbet arkadaşlığı.',
        'name_en': 'Companionship and conversation',
        'description_en': 'Regular visits and conversation so they are not left alone.',
        'icon': 'companion',
        'sort_order': 20,
    },
    {
        'slug': 'hastane-esligi',
        'name': 'Hastane ve doktor eşliği',
        'description': 'Randevulara gidiş dönüşte ve muayene sırasında eşlik.',
        'name_en': 'Hospital and doctor escort',
        'description_en': 'Company on the way to appointments and during examinations.',
        'icon': 'hospital',
        'sort_order': 30,
    },
    {
        'slug': 'alisveris-ev-isleri',
        'name': 'Alışveriş ve ev işleri',
        'description': 'Market, eczane alışverişi ve hafif ev işleri.',
        'name_en': 'Shopping and housework',
        'description_en': 'Grocery and pharmacy shopping and light housework.',
        'icon': 'shopping',
        'sort_order': 40,
    },
    {
        'slug': 'saglik-takibi',
        'name': 'Sağlık takibi',
        'description': 'İlaç saatleri, tansiyon ve şeker ölçümü takibi.',
        'name_en': 'Health monitoring',
        'description_en': 'Tracking medication times, blood pressure and blood sugar.',
        'icon': 'health',
        'sort_order': 50,
    },
    {
        'slug': 'kucuk-tamir',
        'name': 'Küçük ev tamiri',
        'description': 'Ampul, musluk, priz gibi küçük onarımlar.',
        'name_en': 'Small home repairs',
        'description_en': 'Small fixes such as light bulbs, taps and sockets.',
        'icon': 'repair',
        'sort_order': 60,
    },
]
