# Generated by Django 5.2.18 on 2026-10-07 14:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elder_full_name', models.CharField(max_length=150, verbose_name='elder full name')),
                ('elder_age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(120)], verbose_name='elder age')),
                ('relationship', models.CharField(choices=[('parent', 'Mother / father'), ('grandparent', 'Grandparent'), ('relative', 'Other relative'), ('neighbor', 'Neighbor / friend'), ('self', 'Myself')], max_length=20, verbose_name='relationship')),
                ('elder_notes', models.TextField(blank=True, verbose_name='special notes')),
                ('preferred_date', models.DateField(verbose_name='preferred date')),
                ('time_slot', models.CharField(choices=[('morning', 'Morning (08:00-12:00)'), ('afternoon', 'Afternoon (12:00-17:00)'), ('evening', 'Evening (17:00-21:00)')], max_length=20, verbose_name='time slot')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('district', models.CharField(max_length=50, verbose_name='district')),
                ('address', models.TextField(verbose_name='address')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact phone')),
                ('alternate_contact_name', models.CharField(blank=True, max_length=150, verbose_name='alternate contact name')),
                ('alternate_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='alternate contact phone')),
                ('consent_given_at', models.DateTimeField(verbose_name='consent given at')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_requests', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='care.servicetype', verbose_name='service')),
            ],
            options={
                'verbose_name': 'care request',
                'verbose_name_plural': 'care requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
