# Generated by Django 5.2.18 on 2026-10-07 15:31

from django.conf import settings
from django.db import migrations, models

from apps.care.text import person_name_key


def fill_elder_name_keys(apps, schema_editor):
    """
    Mevcut taleplerin yaşlı adı karşılaştırma anahtarlarını doldurur.

    Args:
        apps (StateApps): Migration anındaki model kayıtları.
        schema_editor (BaseDatabaseSchemaEditor): Şema düzenleyici.
    """
    CareRequest = apps.get_model('care', 'CareRequest')
    for care_request in CareRequest.objects.only('id', 'elder_full_name').iterator():
        CareRequest.objects.filter(pk=care_request.pk).update(
            elder_name_key=person_name_key(care_request.elder_full_name),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_carerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequest',
            name='elder_name_key',
            field=models.CharField(default='', editable=False, max_length=150, verbose_name='elder name key'),
        ),
        migrations.RunPython(fill_elder_name_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='carerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'reviewing', 'assigned'])), fields=('applicant', 'service', 'elder_name_key'), name='care_request_unique_open_per_elder_service'),
        ),
    ]
