# Generated by Django 5.2.18 on 2026-10-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_unique_open_request_per_elder_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('message', models.TextField(verbose_name='description')),
                ('consent_given_at', models.DateTimeField(verbose_name='consent given at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='care.servicetype', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service inquiry',
                'verbose_name_plural': 'service inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
