# Generated by Django 5.2.18 on 2026-10-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_service_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='description (English)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='name (English)'),
        ),
    ]
