# Generated by Django 5.2.18 on 2026-10-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_copy_service_type_translations'),
    ]

    operations = [
        # Geri alırken sütunlar boş varsayılanla yeniden eklenebilsin; değerleri 0008'in geri yolu doldurur.
        migrations.AlterField(
            model_name='servicetype',
            name='legacy_name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='legacy_description',
            field=models.CharField(default='', max_length=255, verbose_name='description'),
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='legacy_description',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='legacy_name',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='name_en',
        ),
    ]
